import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center items-center h-screen">
          <div className="flex w-[85vw] h-[80vh] bg-gray-100 rounded-4xl shadow-md">
            <Sidebar />
            <div className="w-[80%] px-10 pt-15 rounded-r-4xl border border-gray-300">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
